
export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';

export const GET_APPOINTMENT_BY_ID_REQUEST = 'GET_APPOINTMENT_BY_ID_REQUEST';
export const GET_APPOINTMENT_BY_ID_SUCCESS = 'GET_APPOINTMENT_BY_ID_SUCCESS';
export const GET_APPOINTMENT_BY_ID_FAILURE = 'GET_APPOINTMENT_BY_ID_FAILURE';



export const GET_ALL_APPOINTMENTS_REQUEST = 'GET_ALL_APPOINTMENTS_REQUEST';
export const GET_ALL_APPOINTMENTS_SUCCESS = 'GET_ALL_APPOINTMENTS_SUCCESS';
export const GET_ALL_APPOINTMENTS_FAILURE = 'GET_ALL_APPOINTMENTS_FAILURE';
