//DOCTOR


export const GET_DOCTOR_LOGIN_DATA_REQUEST = "GET_LOGIN_DATA_REQUEST";
export const GET_DOCTOR_LOGIN_DATA_REQUEST_FAIL = "GET_LOGIN_DATA_REQUEST_FAIL";
export const GET_DOCTOR_LOGIN_DATA_REQUEST_SUCCESS = "GET_LOGIN_DATA_REQUEST_SUCCESS";
export const GET_DOCTOR_LOGIN_DATA_REQUEST_ERROR = "GET_LOGIN_DATA_REQUEST_ERROR";





export const GET_DOCTORS_REQUEST = 'GET_DOCTORS_REQUEST';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const GET_DOCTORS_FAILURE = 'GET_DOCTORS_FAILURE';

export const ADD_DOCTOR_REQUEST = 'ADD_DOCTOR_REQUEST';
export const ADD_DOCTOR_SUCCESS = 'ADD_DOCTOR_SUCCESS';
export const ADD_DOCTOR_FAILURE = 'ADD_DOCTOR_FAILURE';

export const UPDATE_DOCTOR_REQUEST = 'UPDATE_DOCTOR_REQUEST';
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS';
export const UPDATE_DOCTOR_FAILURE = 'UPDATE_DOCTOR_FAILURE';

export const DELETE_DOCTOR_REQUEST = 'DELETE_DOCTOR_REQUEST';
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS';
export const DELETE_DOCTOR_FAILURE = 'DELETE_DOCTOR_FAILURE';
