export const GET_PATIENT_LOGIN_DATA_REQUEST = "GET_LOGIN_DATA_REQUEST";
export const GET_PATIENT_LOGIN_DATA_REQUEST_FAIL = "GET_LOGIN_DATA_REQUEST_FAIL";
export const GET_PATIENT_LOGIN_DATA_REQUEST_SUCCESS = "GET_LOGIN_DATA_REQUEST_SUCCESS";
export const GET_PATIENT_LOGIN_DATA_REQUEST_ERROR = "GET_LOGIN_DATA_REQUEST_ERROR";


export const GET_PATIENT_REGISTER_DATA_REQUEST = "GET_REGISTER_DATA_REQUEST";
export const GET_PATIENT_REGISTER_DATA_REQUEST_FAIL = "GET_REGISTER_DATA_REQUEST_FAIL";
export const GET_PATIENT_REGISTER_DATA_REQUEST_SUCCESS = "GET_REGISTER_DATA_REQUEST_SUCCESS";
export const GET_PATIENT_REGISTER_DATA_REQUEST_ERROR = "GET_REGISTER_DATA_REQUEST_ERROR";

// forgot password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_REQUEST_FAIL = "FORGOT_PASSWORD_REQUEST_FAIL";
export const FORGOT_PASSWORD_REQUEST_SUCCESS =
    "FORGOT_PASSWORD_REQUEST_SUCCESS";
export const FORGOT_PASSWORD_REQUEST_ERROR = "FORGOT_PASSWORD_REQUEST_ERROR";

// reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_FAIL = "RESET_PASSWORD_REQUEST_FAIL";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_ERROR = "RESET_PASSWORD_REQUEST_ERROR";